#!/usr/bin/env python3
"""Embed compiled SPIR-V modules as C arrays.

    tools/shaders/embed.py src/vk/shaders/spv src/vk/shaders/spv/shaders_spv.h

Every <name>.spv becomes `vk_spv_<name>` (uint32_t, SPIR-V words) with its
word count `vk_spv_<name>_size`, plus a table listing all of them so the
backend can look a module up by name.
"""
import os
import struct
import sys


def identifier(name: str) -> str:
    return name.replace("-", "_").replace(".", "_")


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    source, target = sys.argv[1], sys.argv[2]
    modules = sorted(f for f in os.listdir(source) if f.endswith(".spv"))
    if not modules:
        print(f"no .spv files in {source}", file=sys.stderr)
        return 1

    lines = [
        "/* Generated by tools/shaders/embed.py — do not edit.",
        " * Source: every .vert and .frag under src/vk/shaders, compiled with",
        " *   glslangValidator -V --target-env vulkan1.0",
        " * Regenerate with tools/shaders/build.sh. */",
        "#ifndef ENJOER_SHADERS_SPV_H",
        "#define ENJOER_SHADERS_SPV_H",
        "#include <stdint.h>",
        "",
    ]
    entries = []
    for module in modules:
        name = identifier(module[:-4])
        with open(os.path.join(source, module), "rb") as handle:
            blob = handle.read()
        if len(blob) % 4:
            print(f"{module}: not a whole number of SPIR-V words", file=sys.stderr)
            return 1
        words = struct.unpack(f"<{len(blob) // 4}I", blob)
        entries.append((name, len(words)))
        lines.append(f"static const uint32_t vk_spv_{name}[{len(words)}] = {{")
        for offset in range(0, len(words), 8):
            chunk = ", ".join(f"0x{word:08x}u" for word in words[offset:offset + 8])
            lines.append(f"    {chunk},")
        lines.append("};")
        lines.append(f"#define vk_spv_{name}_size {len(words)}")
        lines.append("")

    lines.append("typedef struct { const char *name; const uint32_t *words; uint32_t count; } ShaderModule;")
    lines.append("static const ShaderModule vk_shader_modules[] = {")
    for name, count in entries:
        lines.append(f'    {{ "{name}", vk_spv_{name}, vk_spv_{name}_size }},')
    lines.append("};")
    lines.append("#define VK_SHADER_MODULE_COUNT (sizeof(vk_shader_modules)/sizeof(vk_shader_modules[0]))")
    lines.append("")
    lines.append("#endif")

    with open(target, "w") as handle:
        handle.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
