/* Dump the frame a game produces, for the cross-implementation parity tests.
 *
 *     frame_dump <game-dir> [frames] [dt]
 *
 * Built twice by the tests: once against the VM (the shipping interpreter) and
 * once with -DENJOER_AOT_DRIVER=1 against C generated by the DimScript compiler.
 * Both print the same dump format, so `tools/tests/parity.py` can compare the VM
 * with the Python reference interpreter and `tools/tests/aot.py` can compare it
 * with compiled code.  Coordinates are printed with three decimals, which is
 * what both sides round to. */
#include "engine.h"
#include "enjoer_draw.h"
#include "dimscript_runtime.h"
#include "ds_manifest.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef ENJOER_AOT_DRIVER
#define ENJOER_AOT_DRIVER 0
#endif

#define FRAME_WIDTH 640
#define FRAME_HEIGHT 360

static long fixed(float value) {
    /* Three decimals, matching the interpreter's round(v * 1000). */
    return lroundf(value * 1000.0f);
}

#if ENJOER_AOT_DRIVER

/* The game is machine code: `dimscript_*` from the generated C, running on the
 * same runtime, so the only difference is who executes the script. */
#include "shapes.h"

static void driver_start(void) {
    dimscript_init();
    dimscript_load();
}
static void driver_resized(double width, double height) {
    dimscript_resized((float)width, (float)height);
}
static void driver_update(double delta) { dimscript_update((float)delta); }
static void driver_draw(void) { dimscript_draw(); }
static const char *driver_error(void) { return ""; }

#else

#include "ds_files.h"
#include "ds_vm.h"

static DsVM *vm;

static void driver_start(void) {
    if (!ds_vm_start(vm)) {
        fprintf(stderr, "start: %s\n", ds_vm_error(vm));
        exit(1);
    }
}
static void driver_resized(double width, double height) {
    ds_vm_call_two_numbers(vm, "resized", width, height);
}
static void driver_update(double delta) {
    ds_vm_set_budget(vm, 2000000);
    ds_vm_call_number(vm, "update", delta);
}
static void driver_draw(void) { ds_vm_call_void(vm, "draw"); }
static const char *driver_error(void) { return ds_vm_error(vm); }

static void module_name(const char *file, char *out, size_t capacity) {
    const char *base = file;
    for (const char *cursor = file; *cursor; ++cursor)
        if (*cursor == '/' || *cursor == '\\') base = cursor + 1;
    snprintf(out, capacity, "%s", base);
    char *dot = strrchr(out, '.');
    if (dot) *dot = '\0';
}

static int add_script(const char *file) {
    size_t length = 0;
    char *source = ds_files_read(file, &length);
    if (!source) {
        fprintf(stderr, "нет файла %s\n", file);
        return 0;
    }
    char module[DS_FILES_NAME];
    module_name(file, module, sizeof(module));
    const int ok = ds_vm_add_source(vm, module, source, length);
    free(source);
    if (!ok) fprintf(stderr, "%s: %s\n", file, ds_vm_error(vm));
    return ok;
}

/* Load exactly the way the engine does: the manifest order when there is one,
 * otherwise every .ds file in the folder. */
static int load_game(const DsGameManifest *manifest) {
    int loaded = 0;
    if (manifest->script_count > 0) {
        for (int index = 0; index < manifest->script_count; ++index) {
            if (!add_script(manifest->scripts[index])) return 0;
            ++loaded;
        }
        return loaded > 0;
    }
    char names[32][DS_FILES_NAME];
    const int count = ds_files_list_ds(names, 32);
    for (int index = 0; index < count; ++index) {
        if (!add_script(names[index])) return 0;
        ++loaded;
    }
    return loaded > 0;
}

#endif /* ENJOER_AOT_DRIVER */

static void print_frame(const DsGameManifest *manifest, int frames) {
    const EnjoerFrame *frame = enjoer_frame();
    unsigned long hash = 2166136261ul;
    for (int index = 0; index < frame->vertex_count; ++index) {
        const EnjoerVertex *vertex = &frame->vertices[index];
        const long parts[5] = {fixed(vertex->x), fixed(vertex->y), fixed(vertex->r),
                               fixed(vertex->g), fixed(vertex->b)};
        for (int part = 0; part < 5; ++part)
            hash = (hash ^ (unsigned long)parts[part]) * 16777619ul;
    }
    printf("title %s\n", manifest->title);
    printf("size %d %d\n", FRAME_WIDTH, FRAME_HEIGHT);
    printf("frames %d\n", frames);
    printf("vertices %d\n", frame->vertex_count);
    printf("clear %ld %ld %ld\n", fixed(frame->clear_color[0]), fixed(frame->clear_color[1]),
           fixed(frame->clear_color[2]));
    for (int index = 0; index < frame->vertex_count; ++index) {
        const EnjoerVertex *vertex = &frame->vertices[index];
        printf("v %d %ld %ld %ld %ld %ld\n", index, fixed(vertex->x), fixed(vertex->y),
               fixed(vertex->r), fixed(vertex->g), fixed(vertex->b));
    }
    printf("texts %d\n", frame->text_count);
    for (int index = 0; index < frame->text_count; ++index) {
        const EnjoerTextCommand *text = &frame->texts[index];
        printf("t %d %ld %ld %ld %ld %ld %ld %s\n", index, fixed(text->x), fixed(text->y),
               fixed(text->scale), fixed(text->r), fixed(text->g), fixed(text->b), text->text);
    }
    printf("hash %lu\n", hash);
    printf("error %s\n", driver_error());
}

int main(int argc, char **argv) {
    const char *directory = argc > 1 ? argv[1] : "games/brick";
    const int frames = argc > 2 ? atoi(argv[2]) : 4;
    const double dt = argc > 3 ? atof(argv[3]) : 1.0 / 60.0;

    DsGameManifest manifest;
    ds_manifest_default(&manifest);
#if ENJOER_AOT_DRIVER
    (void)directory;
    snprintf(manifest.title, sizeof(manifest.title), "Shapes (AOT)");
#else
    ds_files_set_root(directory);
    size_t length = 0;
    char *manifest_text = ds_files_read(DS_MANIFEST_NAME, &length);
    if (manifest_text) {
        if (!ds_manifest_parse(&manifest, manifest_text, length)) {
            fprintf(stderr, "game.manifest: %s\n", manifest.error);
            return 1;
        }
        free(manifest_text);
    }
    vm = ds_vm_create();
    if (!vm) return 1;
    if (!load_game(&manifest)) {
        fprintf(stderr, "load: %s\n", ds_vm_error(vm));
        return 1;
    }
    if (!ds_vm_link(vm)) {
        fprintf(stderr, "link: %s\n", ds_vm_error(vm));
        return 1;
    }
#endif

    ds_engine_reset(FRAME_WIDTH, FRAME_HEIGHT);
    driver_start();
    driver_resized(FRAME_WIDTH, FRAME_HEIGHT);

    double clock = 0.0;
    for (int frame = 0; frame < frames; ++frame) {
        clock += dt;
        ds_engine_new_frame(clock, dt, 1.0 / dt);
        driver_update(dt);
        /* The host owns the batch: same begin/end the preview and the APK do. */
        enjoer_frame_begin(FRAME_WIDTH, FRAME_HEIGHT);
        driver_draw();
        enjoer_frame_end();
    }

    print_frame(&manifest, frames);
#if !ENJOER_AOT_DRIVER
    ds_vm_destroy(vm);
#endif
    return 0;
}
