/* STRICT COMPILER MODE — NO VM, ONLY AOT
 * frame_dump <game-dir> [frames] [dt]
 * Built only against C generated by DimScript compiler.
 * AOT to machine code, manual memory, speed like C.
 */
#include "engine.h"
#include "enjoer_draw.h"
#include "dimscript_runtime.h"
#include "ds_manifest.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define FRAME_WIDTH 640
#define FRAME_HEIGHT 360

static long fixed(float value) {
    return lroundf(value * 1000.0f);
}

/* AOT game: dimscript_* from generated C */
#include "shapes.h"

static void driver_start(void) {
    dimscript_init();
    dimscript_load();
}
static void driver_resized(double width, double height) {
    dimscript_resized((float)width, (float)height);
}
static void driver_update(double delta) { dimscript_update((float)delta); }
static void driver_draw(void) { dimscript_draw(); }
static const char *driver_error(void) { return ""; }

static void print_frame(const DsGameManifest *manifest, int frames) {
    const EnjoerFrame *frame = enjoer_frame();
    unsigned long hash = 2166136261ul;
    for (int index = 0; index < frame->vertex_count; ++index) {
        const EnjoerVertex *vertex = &frame->vertices[index];
        const long parts[5] = {fixed(vertex->x), fixed(vertex->y), fixed(vertex->r),
                               fixed(vertex->g), fixed(vertex->b)};
        for (int part = 0; part < 5; ++part)
            hash = (hash ^ (unsigned long)parts[part]) * 16777619ul;
    }
    printf("title %s\n", manifest->title);
    printf("size %d %d\n", FRAME_WIDTH, FRAME_HEIGHT);
    printf("frames %d\n", frames);
    printf("vertices %d\n", frame->vertex_count);
    printf("clear %ld %ld %ld\n", fixed(frame->clear_color[0]), fixed(frame->clear_color[1]),
           fixed(frame->clear_color[2]));
    for (int index = 0; index < frame->vertex_count; ++index) {
        const EnjoerVertex *vertex = &frame->vertices[index];
        printf("v %d %ld %ld %ld %ld %ld\n", index, fixed(vertex->x), fixed(vertex->y),
               fixed(vertex->r), fixed(vertex->g), fixed(vertex->b));
    }
    printf("texts %d\n", frame->text_count);
    for (int index = 0; index < frame->text_count; ++index) {
        const EnjoerTextCommand *text = &frame->texts[index];
        printf("t %d %ld %ld %ld %ld %ld %ld %s\n", index, fixed(text->x), fixed(text->y),
               fixed(text->scale), fixed(text->r), fixed(text->g), fixed(text->b), text->text);
    }
    printf("hash %lu\n", hash);
    printf("error %s\n", driver_error());
}

int main(int argc, char **argv) {
    const char *directory = argc > 1 ? argv[1] : "games/brick";
    const int frames = argc > 2 ? atoi(argv[2]) : 4;
    const double dt = argc > 3 ? atof(argv[3]) : 1.0 / 60.0;

    DsGameManifest manifest;
    ds_manifest_default(&manifest);
    (void)directory;
    snprintf(manifest.title, sizeof(manifest.title), "Shapes (AOT)");

    ds_engine_reset(FRAME_WIDTH, FRAME_HEIGHT);
    driver_start();
    driver_resized(FRAME_WIDTH, FRAME_HEIGHT);

    double clock = 0.0;
    for (int frame = 0; frame < frames; ++frame) {
        clock += dt;
        ds_engine_new_frame(clock, dt, 1.0 / dt);
        driver_update(dt);
        enjoer_frame_begin(FRAME_WIDTH, FRAME_HEIGHT);
        driver_draw();
        enjoer_frame_end();
    }

    print_frame(&manifest, frames);
    return 0;
}
