#ifndef STUB_KEYCODES_H
#define STUB_KEYCODES_H
enum {
  AKEYCODE_BACK = 4, AKEYCODE_0 = 7, AKEYCODE_1 = 8, AKEYCODE_2 = 9,
  AKEYCODE_3 = 10, AKEYCODE_4 = 11, AKEYCODE_5 = 12, AKEYCODE_6 = 13,
  AKEYCODE_DPAD_UP = 19, AKEYCODE_DPAD_DOWN = 20, AKEYCODE_DPAD_LEFT = 21,
  AKEYCODE_DPAD_RIGHT = 22, AKEYCODE_A = 29, AKEYCODE_D = 32, AKEYCODE_E = 33,
  AKEYCODE_F = 34, AKEYCODE_M = 41, AKEYCODE_R = 46, AKEYCODE_S = 47,
  AKEYCODE_W = 51, AKEYCODE_SHIFT_LEFT = 59, AKEYCODE_SHIFT_RIGHT = 60,
  AKEYCODE_SPACE = 62, AKEYCODE_ESCAPE = 111
};
#endif
