#!/bin/sh
# Regenerate src/shaders/draw_spv.h from the GLSL sources.
# Needs glslangValidator (Vulkan SDK or the glslang-tools package).
set -eu
cd "$(dirname "$0")/../.."
GLSLANG=${GLSLANG:-glslangValidator}
OUT=src/shaders/draw_spv.h
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
"$GLSLANG" -V --target-env vulkan1.0 -S vert src/shaders/draw.vert -o "$TMP/vert.spv"
"$GLSLANG" -V --target-env vulkan1.0 -S frag src/shaders/draw.frag -o "$TMP/frag.spv"
{
    printf '/* Generated by tools/shaders/compile.sh from src/shaders/draw.{vert,frag}. */\n'
    printf '#ifndef ENJOER_DRAW_SPV_H\n#define ENJOER_DRAW_SPV_H\n#include <stdint.h>\n'
    for stage in vert frag; do
        printf 'static const uint32_t draw_%s_spv[] = {\n' "$stage"
        od -An -v -tx4 -w32 "$TMP/$stage.spv" | sed 's/ \([0-9a-f]\{8\}\)/ 0x\1,/g'
        printf '};\n'
    done
    printf '#endif\n'
} > "$OUT"
printf 'Wrote %s\n' "$OUT"
