#!/usr/bin/env python3
"""Patch src/shaders/draw_spv.h for the RGBA vertex colour (vec3 -> vec4).

The canonical way to regenerate the header is tools/shaders/compile.sh with
glslangValidator from the Vulkan SDK.  When the SDK is not installed this
script applies the same change directly to the checked-in SPIR-V words.

  vert: in_color/v_color become vec4.  Two pointer types are declared and the
        two OpVariable/OpLoad instructions are re-typed in place (ids and
        word counts stay).
  frag: v_color becomes vec4.  The shape branch stores the colour as-is; the
        textured branch multiplies rgb by v_color.rgb and alpha by v_color.a,
        which costs one VectorShuffle, one CompositeExtract and one FMul.

Safety rails the script runs before writing anything:
  * re-emitting the unpatched modules must reproduce the checked-in header
    byte for byte (serializer round-trip);
  * every cell the patch touches is asserted to hold the exact instruction
    the script expects (no blind pokes);
  * the patched modules are validated: header bound covers every id, sections
    stay ordered, global ids are declared before functions, and every used id
    is defined earlier in the stream.

Usage: python3 tools/shaders/patch_alpha.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HEADER = ROOT / "src" / "shaders" / "draw_spv.h"

OP_ENTRY_POINT = 15
OP_TYPE_VOID = 19
OP_TYPE_FLOAT = 22
OP_TYPE_VECTOR = 23
OP_TYPE_MATRIX = 24
OP_TYPE_POINTER = 32
OP_TYPE_FUNCTION = 33
OP_CONSTANT = 43
OP_FUNCTION = 54
OP_FUNCTION_END = 56
OP_VARIABLE = 59
OP_LOAD = 61
OP_STORE = 62
OP_F_MUL = 133
OP_VECTOR_SHUFFLE = 79
OP_COMPOSITE_CONSTRUCT = 80
OP_COMPOSITE_EXTRACT = 81
OP_COPY_OBJECT = 85

STORAGE_INPUT = 1
STORAGE_OUTPUT = 3


class Ins:
    """One SPIR-V instruction (word 0 + operands)."""

    __slots__ = ("op", "operands")

    def __init__(self, op: int, operands: list[int]):
        self.op = op
        self.operands = list(operands)

    def words(self) -> list[int]:
        return [((1 + len(self.operands)) << 16) | self.op] + self.operands


def parse_header(text: str) -> dict[str, list[int]]:
    modules = {}
    for name, body in re.findall(r"static const uint32_t draw_(\w+)_spv\[\] = \{(.*?)\};", text, re.S):
        modules[name] = [int(w, 16) for w in re.findall(r"0x([0-9a-f]{8})", body)]
    return modules


def emit_header(modules: dict[str, list[int]]) -> str:
    out = [
        "/* Generated by tools/shaders/compile.sh from src/shaders/draw.{vert,frag}. */",
        "#ifndef ENJOER_DRAW_SPV_H",
        "#define ENJOER_DRAW_SPV_H",
        "#include <stdint.h>",
    ]
    for name in ("vert", "frag"):
        out.append(f"static const uint32_t draw_{name}_spv[] = {{")
        words = modules[name]
        for offset in range(0, len(words), 8):
            chunk = words[offset : offset + 8]
            # Compile.sh's od|sed pipeline leaves the very last word comma-less.
            out.append(
                "".join(
                    f" 0x{w:08x}," if offset + i + 1 < len(words) else f" 0x{w:08x}"
                    for i, w in enumerate(chunk)
                )
            )
        out.append("};")
    out.append("#endif")
    return "\n".join(out) + "\n"


def split(words: list[int]) -> tuple[list[int], list[Ins]]:
    header, body = words[:5], []
    index = 5
    while index < len(words):
        packed = words[index]
        op, count = packed & 0xFFFF, packed >> 16
        if count == 0 or index + count > len(words):
            raise SystemExit(f"corrupt instruction stream at word {index}")
        body.append(Ins(op, words[index + 1 : index + count]))
        index += count
    return header, body


def join(header: list[int], body: list[Ins]) -> list[int]:
    words = list(header)
    for ins in body:
        words.extend(ins.words())
    return words


def single_index(body: list[Ins], op: int, operand_slot: int, want: int) -> int:
    hits = [
        i
        for i, ins in enumerate(body)
        if ins.op == op
        and len(ins.operands) > operand_slot
        and ins.operands[operand_slot] == want
    ]
    if len(hits) != 1:
        raise SystemExit(
            f"expected exactly one op {op} with operand[{operand_slot}]={want}, got {len(hits)}"
        )
    return hits[0]


def single(body: list[Ins], op: int) -> int:
    hits = [i for i, ins in enumerate(body) if ins.op == op]
    if len(hits) != 1:
        raise SystemExit(f"expected exactly one op{op}, found {len(hits)}")
    return hits[0]


def find_variable(body: list[Ins], result_id: int) -> int:
    hits = [
        i
        for i, ins in enumerate(body)
        if ins.op == OP_VARIABLE and len(ins.operands) >= 2 and ins.operands[1] == result_id
    ]
    if len(hits) != 1:
        raise SystemExit(f"expected one OpVariable %{result_id}, found {len(hits)}")
    return hits[0]


def find_loads_of(body: list[Ins], pointer_id: int) -> list[int]:
    return [
        i
        for i, ins in enumerate(body)
        if ins.op == OP_LOAD and len(ins.operands) >= 3 and ins.operands[2] == pointer_id
    ]


def patch_vertex(body: list[Ins]) -> tuple[int, int]:
    """vec3 -> vec4 colour for the vertex stage.  Returns (old_bound, new_bound)."""
    # Ground truth from the checked-in module: %7 = vec4 float, %23 = vec3
    # float, %36 = v_color (ptr Output %35 to vec3), %37 = in_color (ptr
    # Input %24 to vec3), the colour OpLoad has result type %23 reading %37.
    out_var = find_variable(body, 36)
    in_var = find_variable(body, 37)
    color_load = find_loads_of(body, 37)
    if len(color_load) != 1:
        raise SystemExit(f"vertex: expected one colour OpLoad, found {len(color_load)}")
    if body[out_var].operands[0] != 35 or body[in_var].operands[0] != 24:
        raise SystemExit("vertex: unexpected pointer types on the colour variables")
    if body[color_load[0]].operands[0] != 23:
        raise SystemExit("vertex: unexpected colour OpLoad result type")

    # The pointers reference %7 (vec4), so they must land immediately after
    # its declaration: forward references between types are not legal SPIR-V
    # (an early OpTypePointer to float precedes %7 in this module, so keying
    # off "the first pointer" is not safe).
    vec4_decl = single_index(body, OP_TYPE_VECTOR, 0, 7)
    body[vec4_decl + 1 : vec4_decl + 1] = [
        Ins(OP_TYPE_POINTER, [51, STORAGE_INPUT, 7]),
        Ins(OP_TYPE_POINTER, [52, STORAGE_OUTPUT, 7]),
    ]
    body[out_var + 2].operands[0] = 52
    body[in_var + 2].operands[0] = 51
    body[color_load[0] + 2].operands[0] = 7
    return 50, 53


def patch_fragment(body: list[Ins]) -> tuple[int, int]:
    """vec4 colour and real alpha math for the fragment stage."""
    # Ground truth: %6 = float, %15 = vec4, %18 = vec3, %19 = ptr Input vec3,
    # %20 = v_color; two OpLoads read %20 (shape branch, textured branch);
    # the shape branch ends in a vec4(r,g,b,1.0) construct, the textured one
    # in vec4(tinted.rgb, texel.a).
    color_var = find_variable(body, 20)
    if body[color_var].operands[0] != 19 or body[color_var].operands[2] != STORAGE_INPUT:
        raise SystemExit("fragment: unexpected v_color variable")
    loads = find_loads_of(body, 20)
    if len(loads) != 2:
        raise SystemExit(f"fragment: expected two v_color loads, found {len(loads)}")
    shape_load, tinted_load = loads
    for index in loads:
        if body[index].operands[0] != 18:
            raise SystemExit("fragment: unexpected colour load result type")
    shape_loaded_id = body[shape_load].operands[1]
    tinted_loaded_id = body[tinted_load].operands[1]

    constructs = [
        i
        for i, ins in enumerate(body)
        if ins.op == OP_COMPOSITE_CONSTRUCT and ins.operands[0] == 15 and len(ins.operands) == 6
    ]
    if len(constructs) != 2:
        raise SystemExit(f"fragment: expected 2 vec4 constructs, found {len(constructs)}")
    shape_construct, texel_construct = constructs
    if not (shape_load < shape_construct < tinted_load < texel_construct):
        raise SystemExit("fragment: unexpected branch layout")

    shape_extracts = [
        i
        for i in range(shape_load + 1, shape_construct)
        if body[i].op == OP_COMPOSITE_EXTRACT and body[i].operands[2] == shape_loaded_id
    ]
    if len(shape_extracts) != 3:
        raise SystemExit(f"fragment: expected 3 shape extracts, found {len(shape_extracts)}")

    tinted_rgb = next(
        (
            i
            for i in range(tinted_load + 1, texel_construct)
            if body[i].op == OP_F_MUL and tinted_loaded_id in body[i].operands[2:]
        ),
        None,
    )
    if tinted_rgb is None:
        raise SystemExit("fragment: tinted rgb multiply not found")
    tinted_rgb_id = body[tinted_rgb].operands[1]

    # 1) Shape branch: load the vec4 and copy it where the old r,g,b,1
    # composite landed; drop the three scalar extracts and the composite.
    stored_id = body[shape_construct].operands[1]
    for i in sorted(shape_extracts + [shape_construct], reverse=True):
        del body[i]
    insert_at = min(shape_extracts + [shape_construct])
    body[shape_load].operands[0] = 15
    body[insert_at:insert_at] = [Ins(OP_COPY_OBJECT, [15, stored_id, shape_loaded_id])]

    # Everything after moved by -(len(shape_extracts) + 1 - 1): patch indexes.
    shift = len(shape_extracts)  # removed 4, added 1 -> -3 == -shift for 3
    tinted_load -= shift
    tinted_rgb -= shift
    texel_construct -= shift

    # 2) Textured branch: tint rgb by v_color.rgb, alpha by v_color.a.
    body[tinted_load].operands[0] = 15
    colour_arg = body[tinted_rgb].operands.index(tinted_loaded_id, 2)
    body[tinted_rgb].operands[colour_arg] = 58
    body[tinted_rgb:tinted_rgb] = [
        Ins(OP_VECTOR_SHUFFLE, [18, 58, tinted_loaded_id, tinted_loaded_id, 0, 1, 2])
    ]
    tinted_rgb += 1
    texel_construct += 1
    texel_alpha_id = body[texel_construct].operands[5]
    anchor = next(
        i
        for i in range(tinted_rgb + 1, texel_construct)
        if body[i].op == OP_COMPOSITE_EXTRACT and body[i].operands[2] == tinted_rgb_id
    )
    body[anchor:anchor] = [
        Ins(OP_COMPOSITE_EXTRACT, [6, 59, tinted_loaded_id, 3]),
        Ins(OP_F_MUL, [6, 60, 59, texel_alpha_id]),
    ]
    texel_construct += 2
    body[texel_construct].operands[5] = 60

    # 3) The v_color variable loads through the new vec4 pointer type.  Its
    # declaration must come after the vec4 type (%15) it points at — an
    # OpTypePointer-to-float precedes %15 in this module, so the new pointer
    # goes immediately after the vector declaration itself.
    body[color_var].operands[0] = 57
    vec4_decl = single_index(body, OP_TYPE_VECTOR, 0, 15)
    body[vec4_decl + 1 : vec4_decl + 1] = [Ins(OP_TYPE_POINTER, [57, STORAGE_INPUT, 15])]
    return 57, 61


def validate(header: list[int], body: list[Ins], name: str) -> None:
    """Structural sanity: SPIR-V allows forward references at module scope
    (OpEntryPoint names its function and interface before they are declared),
    but type/constant/global-variable declarations must all precede the
    functions, and SSA ids inside a function must be defined before use."""
    bound = header[3]
    if header[0] != 0x07230203:
        raise SystemExit(f"{name}: bad magic")
    # Every id ever referenced and every result-id position: an operand is an
    # id reference unless the op takes none (labels, branches use them too).
    # A conservative structural check is all that is needed here: nothing may
    # reference an id at or past the header bound, declarations must stay out
    # of functions, and the entry function must still exist.
    all_ids = set()
    # Ops whose operands carry string bytes or arbitrary literals; skipping
    # them keeps packed ASCII out of the id scan.  (Their few real ids are
    # referenced elsewhere anyway.)
    literal_ops = {2, 3, 4, 5, 6, 7, 8, 11, 15}
    for ins in body:
        if ins.op not in literal_ops:
            for operand in ins.operands:
                if operand > 0x00FFFFFF:
                    continue  # literal word (float bits etc.), not an id
                all_ids.add(operand)
    max_used = max(all_ids) if all_ids else 0

    seen_function = False
    have_entry_function = False
    for ins in body:
        if ins.op == OP_FUNCTION:
            if seen_function:
                raise SystemExit(f"{name}: nested functions")
            seen_function = True
            have_entry_function = True
            continue
        if ins.op == OP_FUNCTION_END:
            seen_function = False
            continue
        if seen_function and ins.op in (
            OP_TYPE_VOID, OP_TYPE_FLOAT, OP_TYPE_VECTOR, OP_TYPE_MATRIX, OP_TYPE_POINTER,
            15, 16, 17,
        ):
            raise SystemExit(f"{name}: module-scope declaration inside a function (op{ins.op})")
    if not have_entry_function:
        raise SystemExit(f"{name}: no function found")
    if max_used >= bound:
        raise SystemExit(f"{name}: id %{max_used} escapes bound {bound}")


def main() -> int:
    text = HEADER.read_text(encoding="utf-8")
    modules = parse_header(text)
    if emit_header(modules) != text:
        raise SystemExit("round-trip guard failed: serializer does not reproduce the header")

    vert_header, vert_body = split(modules["vert"])
    frag_header, frag_body = split(modules["frag"])

    old_bound, new_bound = patch_vertex(vert_body)
    if vert_header[3] != old_bound:
        raise SystemExit(f"vertex: expected bound {old_bound}, found {vert_header[3]}")
    vert_header[3] = new_bound

    old_bound, new_bound = patch_fragment(frag_body)
    if frag_header[3] != old_bound:
        raise SystemExit(f"fragment: expected bound {old_bound}, found {frag_header[3]}")
    frag_header[3] = new_bound

    modules["vert"] = join(vert_header, vert_body)
    modules["frag"] = join(frag_header, frag_body)

    validate(vert_header, vert_body, "vertex")
    validate(frag_header, frag_body, "fragment")

    HEADER.write_text(emit_header(modules), encoding="utf-8")
    print(
        f"patched {HEADER.relative_to(ROOT)}: vec3->vec4 colour "
        f"(vert {len(modules['vert'])} words, frag {len(modules['frag'])} words)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
