#!/usr/bin/env python3
"""Turn a game folder into the parts an APK needs.

    tools/gamepack.py games/brick --staging staging

The tool does three things and nothing else:

1. validates ``game.manifest`` with the same rules the engine uses, so a broken
   game fails on the host instead of on a phone;
2. copies the manifest, every ``.ds`` file, every image (``images = [...]``,
   ``.png``) and every font (``fonts = [...]``, ``.ttf``/``.otf``) into
   ``assets/game/``, which is where the runtime looks for them
   (``src/ds_files.c``);
3. writes ``AndroidManifest.xml`` from the game manifest — package, label,
   orientation, version.  The XML is generated rather than edited because both
   halves must agree, and a game author should never touch it.

Launcher icons are not supported yet: a game dropped into a ``mipmap-*``
resource tree or an ``icon`` key fails with an explicit message instead of
being silently dropped.  Plain ``icon.png`` sprites are ordinary images now.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from dimscript.lexer import DimScriptError  # noqa: E402
from dimscript.manifest import MANIFEST_NAME, GameManifest, read_manifest  # noqa: E402
from dimscript.project import load_project  # noqa: E402

ACTIVITY_NAME = "com.cb4.GameActivity"
NATIVE_LIBRARY = "ds_game"

#: Magic bytes the packer checks before staging an asset, so a renamed text
#: file fails on the host instead of decoding to garbage on a phone.
PNG_MAGIC = b"\x89PNG\r\n\x1a\n"
FONT_MAGICS = (b"\x00\x01\x00\x00", b"true", b"typ1", b"OTTO")

# key -> (suffixes, magic check): the same lists the engine parses.
ASSET_KEYS: Dict[str, Tuple[Tuple[str, ...], str]] = {
    "images": ((".png",), "png"),
    "fonts": ((".ttf", ".otf"), "font"),
}

TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/gamepack.py from {source}. Do not edit: the engine reads
     the same {manifest} at startup, so both copies must stay in sync. -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="{package}"
    android:versionCode="{version_code}"
    android:versionName="{version}">

    <uses-sdk android:minSdkVersion="{min_sdk}" android:targetSdkVersion="{target_sdk}" />
    <uses-feature android:name="android.hardware.touchscreen" android:required="true" />
    <uses-feature android:name="android.hardware.vulkan.version" android:version="0x400003"
        android:required="true" />

    <application
        android:label="{label}"
        android:hasCode="true"
        android:allowBackup="false"
        android:theme="@android:style/Theme.Black.NoTitleBar.Fullscreen">

        <activity
            android:name="{activity}"
            android:label="{label}"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|screenLayout|uiMode{density}"
            android:screenOrientation="{orientation}"
            android:resizeableActivity="{resizeable}"
            android:windowSoftInputMode="adjustResize|stateHidden"
            android:exported="true">
            <meta-data android:name="android.app.lib_name" android:value="{library}" />
            <meta-data android:name="android.app.game_asset_dir" android:value="game" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
"""


def xml_escape(text: str) -> str:
    replacements = {"&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&apos;"}
    for needle, replacement in replacements.items():
        text = text.replace(needle, replacement)
    return text


def android_manifest(manifest: GameManifest, source: str = MANIFEST_NAME) -> str:
    """Render AndroidManifest.xml from a game manifest."""

    return TEMPLATE.format(
        source=source,
        manifest=MANIFEST_NAME,
        package=xml_escape(manifest.package),
        version_code=manifest.version_code,
        version=xml_escape(manifest.version),
        min_sdk=29,
        target_sdk=34,
        label=xml_escape(manifest.title),
        activity=ACTIVITY_NAME,
        library=NATIVE_LIBRARY,
        orientation=xml_escape(manifest.orientation),
        resizeable="true" if manifest.resizeable else "false",
        density="" if manifest.resizeable else "|density",
    )


def _set_list_key(text: str, key: str, names: Sequence[str]) -> Tuple[str, bool]:
    """Rewrite one ``key = [...]`` line; returns the text and whether it did."""

    wanted = ", ".join(f'"{name}"' for name in names)
    lines = text.splitlines()
    for index, line in enumerate(lines):
        code = line.split("--", 1)[0]
        if code.split("=", 1)[0].strip() != key:
            continue
        if code.split("=", 1)[1].strip() == f"[{wanted}]":
            return text, False
        lines[index] = f"{key} = [{wanted}]"
        return "\n".join(lines) + "\n", True
    return text, False


def normalized_manifest_text(directory: Path, manifest: GameManifest) -> str:
    """The manifest as the packaged game should carry it.

    A device cannot scan ``assets/`` for files, so the file lists the host
    computed from the folder are written back into the copy that ships.
    A hand-written key is kept as-is when it already matches.
    """

    text = (directory / MANIFEST_NAME).read_text(encoding="utf-8")
    missing: List[str] = []
    for key in ("scripts", "images", "fonts"):
        names = getattr(manifest, key)
        if not names and key != "scripts":
            continue
        text, _ = _set_list_key(text, key, names)
        present = any(
            line.split("--", 1)[0].split("=", 1)[0].strip() == key
            for line in text.splitlines()
        )
        if not present:
            quoted = ", ".join('"' + name + '"' for name in names)
            missing.append(f"{key} = [{quoted}]")
    if missing:
        body = text.rstrip("\n")
        text = (
            body
            + "\n\n-- Added by tools/gamepack.py: an Android build can only open files it\n"
            + "-- knows the name of, so the file lists are written into the packaged copy.\n"
            + "\n".join(missing)
            + "\n"
        )
    return text


def find_icon_files(directory: Path) -> List[Path]:
    """A real Android icon tree dropped into the game folder.

    Plain ``icon.png`` sprites are ordinary images since the texture loader
    landed; only ``mipmap-*`` resource trees and ``ic_launcher*`` files are
    still rejected, because those only make sense as a launcher icon.
    """

    found: List[Path] = []
    for path in sorted(directory.rglob("*")):
        if not path.is_file():
            continue
        if path.name.lower().startswith("ic_launcher"):
            found.append(path)
            continue
        if any(part.lower().startswith("mipmap") for part in path.parts):
            found.append(path)
    return found


def script_files(directory: Path, manifest: GameManifest) -> List[Path]:
    listed = [directory / name for name in manifest.scripts]
    extra = sorted(path for path in directory.glob("*.ds") if path not in listed)
    return [path for path in listed + extra if path.exists()]


def _sniff_image_format(header: bytes) -> Optional[str]:
    """Short name of the image format in the first header bytes, else None.

    Mirrors ds_image_format_name in src/ds_image.c: whatever the packer names
    here, the loader on the device refuses with the same name.
    """

    if header[:8] == PNG_MAGIC:
        return "PNG"
    if len(header) >= 3 and header[:3] == b"\xff\xd8\xff":
        return "JPEG"
    if len(header) >= 6 and header[:4] == b"GIF8" and header[4:5] in (b"7", b"9") \
            and header[5:6] == b"a":
        return "GIF"
    if header[:2] == b"BM":
        return "BMP"
    if len(header) >= 12 and header[:4] == b"RIFF" and header[8:12] == b"WEBP":
        return "WebP"
    if header[:4] in (b"II*\x00", b"MM\x00*"):
        return "TIFF"
    return None


def _check_magic(path: Path, kind: str) -> None:
    with open(path, "rb") as stream:
        header = stream.read(12)
    if kind == "png" and header[:8] == PNG_MAGIC:
        return
    if kind == "font" and header[:4] in FONT_MAGICS:
        return
    if kind == "png":
        sniffed = _sniff_image_format(header)
        if sniffed is not None:
            raise DimScriptError(
                f"{path.name}: в images только PNG (это {sniffed} — сконвертируйте картинку в PNG)"
            )
    want = "PNG" if kind == "png" else "TrueType/OpenType"
    raise DimScriptError(f"{path.name}: не {want} (первые байты не совпадают с {want})")


def asset_files(directory: Path, manifest: GameManifest, key: str) -> List[str]:
    """Resolve one asset key to the relative names that ship.

    Listed files must exist; anything else with a matching suffix is picked up
    too (subfolders included), so a forgotten entry stages anyway — the same
    rule scripts follow.
    """

    suffixes, kind = ASSET_KEYS[key]
    listed = list(getattr(manifest, key))
    names: List[str] = []
    for name in listed:
        path = directory / name
        if not path.is_file():
            raise DimScriptError(f"{directory}: '{name}' из '{key}' не найден")
        _check_magic(path, kind)
        names.append(name)
    known = set(names)
    for path in sorted(directory.rglob("*")):
        if not path.is_file() or path.suffix not in suffixes:
            continue
        relative = path.relative_to(directory).as_posix()
        if relative in known:
            continue
        _check_magic(path, kind)
        names.append(relative)
    return names


def pack(directory: Path, staging: Path, *, check_only: bool = False,
         manifest_out: Optional[Path] = None) -> GameManifest:
    """Validate the game, then stage it.  Returns the resolved manifest."""

    directory = directory.resolve()
    if not directory.is_dir():
        raise DimScriptError(f"{directory}: нет такой папки игры (путь должен вести к папке с "
                             f"{MANIFEST_NAME}; текущая директория: {Path.cwd()})")
    project = load_project(directory)
    manifest = project.manifest

    icons = find_icon_files(directory)
    if icons:
        names = ", ".join(path.name for path in icons)
        raise DimScriptError(
            f"иконки лаунчера пока не поддерживаются (найдено: {names}); уберите дерево "
            "mipmap/ic_launcher — обычные картинки кладите через images = [...]"
        )

    scripts = script_files(directory, manifest)
    if not scripts:
        raise DimScriptError(f"{directory}: в игре нет .ds файлов")

    # The runtime on a device only sees what the manifest lists, so the packaged
    # copy always names every file explicitly, in load order.
    manifest.scripts = [path.name for path in scripts]
    manifest.images = asset_files(directory, manifest, "images")
    manifest.fonts = asset_files(directory, manifest, "fonts")

    if check_only:
        return manifest

    target = staging / "assets" / "game"
    if target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True)
    (target / MANIFEST_NAME).write_text(normalized_manifest_text(directory, manifest), encoding="utf-8")
    for path in scripts:
        shutil.copy2(path, target / path.name)
    for name in manifest.images + manifest.fonts:
        destination = target / name
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(directory / name, destination)
    target_manifest = manifest_out or (staging / "AndroidManifest.xml")
    target_manifest.parent.mkdir(parents=True, exist_ok=True)
    target_manifest.write_text(android_manifest(manifest), encoding="utf-8")
    return manifest


def describe(manifest: GameManifest, staging: Path,
             manifest_out: Optional[Path] = None) -> str:
    lines = [
        f"{manifest.title} — {manifest.package} v{manifest.version} "
        f"(code {manifest.version_code}, {manifest.orientation}, {manifest.target_fps} fps)",
        f"  scripts: {', '.join(manifest.scripts)}",
    ]
    if manifest.images:
        lines.append(f"  images:  {', '.join(manifest.images)}")
    if manifest.fonts:
        lines.append(f"  fonts:   {', '.join(manifest.fonts)}")
    lines.append(f"  manifest: {manifest_out or staging / 'AndroidManifest.xml'}")
    lines.append(f"  assets:   {staging / 'assets' / 'game'}")
    return "\n".join(lines)


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(prog="gamepack", description=__doc__.splitlines()[0])
    parser.add_argument("game", nargs="?", default="games/brick", help="папка игры (по умолчанию games/brick)")
    parser.add_argument("--staging", default="staging", help="куда положить assets/game/")
    parser.add_argument("--manifest-out", default=None,
                        help="куда писать AndroidManifest.xml (по умолчанию — внутри --staging). "
                             "aapt не принимает входную папку, в которой уже лежит манифест, "
                             "поэтому сборщик APK выносит его отдельно.")
    parser.add_argument("--check", action="store_true", help="только проверить, ничего не записывая")
    parser.add_argument("--print-manifest", action="store_true", help="напечатать AndroidManifest.xml в stdout")
    args = parser.parse_args(argv)

    try:
        manifest = pack(Path(args.game), Path(args.staging),
                        check_only=args.check or args.print_manifest,
                        manifest_out=Path(args.manifest_out) if args.manifest_out else None)
    except (DimScriptError, OSError) as error:
        print(f"gamepack: error: {error}", file=sys.stderr)
        return 2
    if args.print_manifest:
        sys.stdout.write(android_manifest(manifest))
        return 0
    print(describe(manifest, Path(args.staging),
                   Path(args.manifest_out) if args.manifest_out else None))
    if args.check:
        print("  check only: ничего не записано")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
