#!/usr/bin/env python3
"""Turn a game folder into the parts an APK needs.

    tools/gamepack.py games/brick --staging staging

The tool does three things and nothing else:

1. validates ``game.manifest`` with the same rules the engine uses, so a broken
   game fails on the host instead of on a phone;
2. copies the manifest and every ``.ds`` file into ``assets/game/``, which is
   where the runtime looks for them (``src/ds_files.c``);
3. writes ``AndroidManifest.xml`` from the game manifest — package, label,
   orientation, version.  The XML is generated rather than edited because both
   halves must agree, and a game author should never touch it.

Icons are not supported yet: a game that contains an icon file or an ``icon``
key fails with an explicit message instead of being silently dropped.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path
from typing import List, Optional, Sequence

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from dimscript.lexer import DimScriptError  # noqa: E402
from dimscript.manifest import MANIFEST_NAME, GameManifest, read_manifest  # noqa: E402
from dimscript.project import load_project  # noqa: E402

ICON_SUFFIXES = {".png", ".jpg", ".jpeg", ".webp", ".ico", ".svg", ".icns", ".adm", ".xml"}
ACTIVITY_NAME = "com.cb4.GameActivity"
NATIVE_LIBRARY = "ds_game"

TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/gamepack.py from {source}. Do not edit: the engine reads
     the same {manifest} at startup, so both copies must stay in sync. -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="{package}"
    android:versionCode="{version_code}"
    android:versionName="{version}">

    <uses-sdk android:minSdkVersion="{min_sdk}" android:targetSdkVersion="{target_sdk}" />
    <uses-feature android:name="android.hardware.touchscreen" android:required="true" />
    <uses-feature android:name="android.hardware.vulkan.version" android:version="0x400003"
        android:required="true" />

    <application
        android:label="{label}"
        android:hasCode="true"
        android:allowBackup="false"
        android:theme="@android:style/Theme.Black.NoTitleBar.Fullscreen">

        <activity
            android:name="{activity}"
            android:label="{label}"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|screenLayout|uiMode{density}"
            android:screenOrientation="{orientation}"
            android:resizeableActivity="{resizeable}"
            android:windowSoftInputMode="adjustResize|stateHidden"
            android:exported="true">
            <meta-data android:name="android.app.lib_name" android:value="{library}" />
            <meta-data android:name="android.app.game_asset_dir" android:value="game" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
"""


def xml_escape(text: str) -> str:
    replacements = {"&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&apos;"}
    for needle, replacement in replacements.items():
        text = text.replace(needle, replacement)
    return text


def android_manifest(manifest: GameManifest, source: str = MANIFEST_NAME) -> str:
    """Render AndroidManifest.xml from a game manifest."""

    return TEMPLATE.format(
        source=source,
        manifest=MANIFEST_NAME,
        package=xml_escape(manifest.package),
        version_code=manifest.version_code,
        version=xml_escape(manifest.version),
        min_sdk=29,
        target_sdk=34,
        label=xml_escape(manifest.title),
        activity=ACTIVITY_NAME,
        library=NATIVE_LIBRARY,
        orientation=xml_escape(manifest.orientation),
        resizeable="true" if manifest.resizeable else "false",
        density="" if manifest.resizeable else "|density",
    )


def normalized_manifest_text(directory: Path, manifest: GameManifest) -> str:
    """The manifest as the packaged game should carry it.

    A device cannot scan ``assets/`` for files, so the load order the host
    computed from the folder listing is written back into the copy that ships.
    A hand-written ``scripts`` key is kept as-is when it already matches.
    """

    text = (directory / MANIFEST_NAME).read_text(encoding="utf-8")
    wanted = ", ".join(f'"{name}"' for name in manifest.scripts)
    lines = text.splitlines()
    for index, line in enumerate(lines):
        code = line.split("--", 1)[0]
        if code.split("=", 1)[0].strip() != "scripts":
            continue
        if code.split("=", 1)[1].strip() == f"[{wanted}]":
            return text
        lines[index] = f"scripts = [{wanted}]"
        return "\n".join(lines) + "\n"
    body = text.rstrip("\n")
    suffix = "" if not body or body.endswith("\n") else "\n"
    return (
        body
        + suffix
        + "\n-- Added by tools/gamepack.py: an Android build can only open files it\n"
        + "-- knows the name of, so the load order is written into the packaged copy.\n"
        + f"scripts = [{wanted}]\n"
    )


def find_icon_files(directory: Path) -> List[Path]:
    """Anything that looks like an icon — rejected until the engine can show one."""

    found: List[Path] = []
    for path in sorted(directory.rglob("*")):
        if not path.is_file():
            continue
        if path.name.lower().startswith("ic_launcher") or path.stem.lower() == "icon":
            found.append(path)
            continue
        if path.suffix.lower() in ICON_SUFFIXES and "mipmap" in path.parts:
            found.append(path)
    return found


def script_files(directory: Path, manifest: GameManifest) -> List[Path]:
    listed = [directory / name for name in manifest.scripts]
    extra = sorted(path for path in directory.glob("*.ds") if path not in listed)
    return [path for path in listed + extra if path.exists()]


def pack(directory: Path, staging: Path, *, check_only: bool = False) -> GameManifest:
    """Validate the game, then stage it.  Returns the resolved manifest."""

    directory = directory.resolve()
    if not directory.is_dir():
        raise DimScriptError(f"{directory}: это не папка игры")
    project = load_project(directory)
    manifest = project.manifest

    icons = find_icon_files(directory)
    if icons:
        names = ", ".join(path.name for path in icons)
        raise DimScriptError(
            f"иконки пока не поддерживаются (найдено: {names}); уберите файлы иконок — "
            "растровые ресурсы появятся вместе с загрузчиком текстур"
        )

    scripts = script_files(directory, manifest)
    if not scripts:
        raise DimScriptError(f"{directory}: в игре нет .ds файлов")

    # The runtime on a device only sees what the manifest lists, so the packaged
    # copy always names every file explicitly, in load order.
    manifest.scripts = [path.name for path in scripts]

    if check_only:
        return manifest

    target = staging / "assets" / "game"
    if target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True)
    (target / MANIFEST_NAME).write_text(normalized_manifest_text(directory, manifest), encoding="utf-8")
    for path in scripts:
        shutil.copy2(path, target / path.name)
    (staging / "AndroidManifest.xml").write_text(android_manifest(manifest), encoding="utf-8")
    return manifest


def describe(manifest: GameManifest, staging: Path) -> str:
    return (
        f"{manifest.title} — {manifest.package} v{manifest.version} "
        f"(code {manifest.version_code}, {manifest.orientation}, {manifest.target_fps} fps)\n"
        f"  scripts: {', '.join(manifest.scripts)}\n"
        f"  manifest: {staging / 'AndroidManifest.xml'}\n"
        f"  assets:   {staging / 'assets' / 'game'}"
    )


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(prog="gamepack", description=__doc__.splitlines()[0])
    parser.add_argument("game", nargs="?", default="games/brick", help="папка игры (по умолчанию games/brick)")
    parser.add_argument("--staging", default="staging", help="куда положить assets/ и AndroidManifest.xml")
    parser.add_argument("--check", action="store_true", help="только проверить, ничего не записывая")
    parser.add_argument("--print-manifest", action="store_true", help="напечатать AndroidManifest.xml в stdout")
    args = parser.parse_args(argv)

    try:
        manifest = pack(Path(args.game), Path(args.staging), check_only=args.check or args.print_manifest)
    except (DimScriptError, OSError) as error:
        print(f"gamepack: error: {error}", file=sys.stderr)
        return 2
    if args.print_manifest:
        sys.stdout.write(android_manifest(manifest))
        return 0
    print(describe(manifest, Path(args.staging)))
    if args.check:
        print("  check only: ничего не записано")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
